Encoding support
stanrogo/browser-line-reader pull request #5
Opened 2020-05-31 05:41 UTC by tonila

Hi,

Came across this beaty, but I needed encoding. So here is my pull request.

2020-05-31 08:57 UTC, tonila commented
Reimplemented my first implementation with options API.

`constructor(file: File, options: Options={})`

That triggered multiple pushes, since I haven't done much with Typescipt.

2020-08-10 12:53 UTC, stanrogo requested changes
Nice and simple, I just have some linting issues and then I can merge it. Sorry for the delay @tonila, I hardly ever look at my repos. I should probably see if I can set appropriate email notifications.

2020-08-10 12:53 UTC, stanrogo commented on src/index.ts
> +	public constructor(file: File, options: Options={}) {
```suggestion
	public constructor(file: File, options: Options = { encoding: 'UTF-8' }) {
```

2020-08-10 12:53 UTC, stanrogo commented on src/index.ts
> +		if (!options.encoding) options.encoding = 'UTF-8'
You can then remove this line since it's already in the argument defaults

2020-08-10 12:53 UTC, stanrogo commented on src/index.ts
> +	public constructor(file: File, options: Options={}) {
This is neater in my opinion

2020-08-10 12:53 UTC, stanrogo commented on src/index.d.ts
> +import {Options} from './interfaces';
This and a few other lines are not consistent with the linting rules set out in pritterrc and eslintrc. That's on me that I didn't include proper contribution guidelines (and the pre-commit hooks didn't seem to work). For now, please just accept my suggestions and I'll look into this at some point.

2020-08-10 12:53 UTC, stanrogo commented on src/index.d.ts
> +import {Options} from './interfaces';
```suggestion

import { Options } from './interfaces';
```

2020-08-10 12:53 UTC, stanrogo commented on src/index.ts
> +import {Options} from './interfaces';
```suggestion

import { Options } from './interfaces';
```

2020-08-10 12:53 UTC, stanrogo commented on src/interfaces.ts
> +
```suggestion
```

2020-08-10 12:53 UTC, stanrogo commented on src/interfaces.ts
> +}
```suggestion
}

```

2020-08-11 10:05 UTC, stanrogo approved these changes

2020-08-11 10:06 UTC, merged